# This is a basic workflow to help you get started with Actions

name: DevSecOps

on: [push, pull_request]

jobs:

  scan:
    
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - name: Secret Scan
      uses: max/secret-scan@1.0.0
      
    - name: Check password
      uses: AlicanAkkus/pinder-action@1.0.0
      
    - name: Git Anti Virus Scan
      uses: djdefi/gitavscan@2
      with:
        # Full history scan
        full: '--full'
